# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  weight = 10

[[main]]
  name = "Publications"
  url = "https://scholar.google.com/citations?hl=en&user=6Urve9wAAAAJ&view_op=list_works&sortby=pubdate"
  weight = 20

[[main]]
  name = "CV"
  url = "/files/cv.pdf"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
